export const BOOKS = [
  {
    name: "Atomic Habits",
    image: "https://images-na.ssl-images-amazon.com/images/I/81wgcld4wxL.jpg",
    url: "https://amzn.to/3Smga5z",
    author: "James Clear",
    author_url: "https://amzn.to/3SenUX2",
    asin: "",
    isbn10: "0735211299",
    read: true,
    rating: 4.8,
  },
  {
    name: "Tiny Habits",
    image: "https://images-na.ssl-images-amazon.com/images/I/714QdOmbHDL.jpg",
    url: "https://amzn.to/3xxxsEL",
    author: "B.J. Fogg",
    author_url: "https://amzn.to/3dwtCET",
    asin: "",
    isbn10: "0358003326",
    read: true,
    rating: 5,
  },
  {
    name: "You Don't Know JS",
    image: "https://images-na.ssl-images-amazon.com/images/I/71mKvD89oEL.jpg",
    url: "https://amzn.to/3f4B6zB",
    author: "Kyle Simpson",
    author_url: "https://amzn.to/3BW4rFu",
    asin: "",
    isbn10: "9789352136261",
    read: true,
    rating: 3.8,
  },
  {
    name: "Dune",
    image: "https://images-na.ssl-images-amazon.com/images/I/A1u+2fY5yTL.jpg",
    url: "https://amzn.to/3RW6LSr",
    author: "Frank Herbert",
    author_url: "https://amzn.to/3eWYXRv",
    asin: "",
    isbn10: "059309932X",
    read: true,
    rating: 4.5,
  },
  {
    name: "The Little Prince",
    image: "https://images-na.ssl-images-amazon.com/images/I/71OZY035QKL.jpg",
    url: "https://amzn.to/3Sd0aCC",
    author: "Antoine de Saint-Exupéry",
    author_url: "https://amzn.to/3BwkS9L",
    asin: "",
    isbn10: "0156012197",
    read: true,
    rating: 4.1,
  },
  {
    name: "The Subtle Art of Not Giving a F*ck",
    image: "https://images-na.ssl-images-amazon.com/images/I/81tjorIkScL.jpg",
    url: "https://amzn.to/3qTLVXG",
    author: "Mark Manson",
    author_url: "https://amzn.to/3BwkS9L",
    asin: "B09LSWSCL8",
    isbn10: "",
    read: true,
    rating: 2.8,
  },
  {
    name: "The Algorithm Design Manual",
    image: "https://images-na.ssl-images-amazon.com/images/I/41xbSBf4oFL.jpg",
    url: "https://amzn.to/3SaP6WU",
    author: "Steven S. Skiena",
    author_url: "https://amzn.to/3BUmRX5",
    asin: "",
    isbn10: "1848000693",
    read: false,
    rating: 0,
  },
  {
    name: "The 5am Club",
    image: "https://images-na.ssl-images-amazon.com/images/I/71wKvkBthPL.jpg",
    url: "https://amzn.to/3Uq7QU8",
    author: "Robin S. Sharma",
    author_url: "https://amzn.to/3LrCJmS",
    asin: "",
    isbn10: "1443460710",
    read: false,
    rating: 0,
  },
  {
    name: "People Skills: How to Assert Yourself, Listen to Others, and Resolve Conflicts",
    image: "https://images-na.ssl-images-amazon.com/images/I/617YRS1p9WL.jpg",
    url: "https://amzn.to/3qOcxtk",
    author: "Robert Bolton",
    author_url: "https://amzn.to/3f7imQ5",
    asin: "",
    isbn10: "9780671622480",
    read: true,
    rating: 4.6,
  },
  {
    name: "This Is How You Lose Her",
    image: "https://images-na.ssl-images-amazon.com/images/I/81OZawQIuPL.jpg",
    url: "https://amzn.to/3qP1dgD",
    author: "Junot Díaz",
    author_url: "https://amzn.to/3eS3VyX",
    asin: "",
    isbn10: "1594631778",
    read: false,
    rating: 0,
  },
  {
    name: "Functional JavaScript",
    image: "https://images-na.ssl-images-amazon.com/images/I/51Pc6VPaBAL.jpg",
    url: "https://amzn.to/3DUGRdF",
    author: "Michael Fogus",
    author_url: "https://amzn.to/3R5JuME",
    asin: "",
    isbn10: "9781449360726",
    read: true,
    rating: 4.1,
  },
  {
    name: "The Hitchhiker's Guide to the Galaxy",
    image: "https://images-na.ssl-images-amazon.com/images/I/81XSN3hA5gL.jpg",
    url: "https://amzn.to/3Bstrmg",
    author: "Douglas Adams",
    author_url: "0345391802",
    asin: "",
    isbn10: "0345391802",
    read: true,
    rating: 4.8,
  },
  {
    name: "Extreme Ownership: How U.S. Navy SEALs Lead and Win",
    image: "https://images-na.ssl-images-amazon.com/images/I/815g1O76zBL.jpg",
    url: "https://amzn.to/3f4G7Ir",
    author: "Jocko Willink",
    author_url: "https://amzn.to/3QY8cOA",
    asin: "",
    isbn10: "0345391802",
    read: true,
    rating: 4.2,
  },
  {
    name: "Never Split the Difference",
    image: "https://images-na.ssl-images-amazon.com/images/I/41OPh6SpYuL.jpg",
    url: "https://amzn.to/3QSBSwB",
    author: "Chris Voss",
    author_url: "https://amzn.to/3QY8cOA",
    asin: "B08W57YLHR",
    isbn10: "",
    read: true,
    rating: 4.9,
  },
  {
    name: "Ikigai: The Japanese Secret to a Long and Happy Life",
    image: "https://images-na.ssl-images-amazon.com/images/I/71tbalAHYCL.jpg",
    url: "https://amzn.to/3f53gu4",
    author: "Héctor García",
    author_url: "https://amzn.to/3DEsnym",
    asin: "",
    isbn10: "0143130722",
    read: true,
    rating: 3.9,
  },
  {
    name: "Designing Data-Intensive Applications",
    image: "https://m.media-amazon.com/images/P/1449373321.01._SCLZZZZZZZ_SX500_.jpg",
    url: "https://amzn.to/3qSCQP2",
    author: "Martin Kleppmann",
    author_url: "https://amzn.to/3qS7A2w",
    asin: "",
    isbn10: "1449373321",
    read: true,
    rating: 4,
  },
  {
    name: "Rich Dad Poor Dad",
    image: "https://images-na.ssl-images-amazon.com/images/I/81bsw6fnUiL.jpg",
    url: "https://amzn.to/3Sgqn3o",
    author: "Robert T. Kiyosaki",
    author_url: "https://amzn.to/3UzHRtw",
    asin: "",
    isbn10: "1612680194",
    read: true,
    rating: 4.1,
  },
  {
    name: "Mastery",
    image: "https://images-na.ssl-images-amazon.com/images/I/71LRdEUOmNL.jpg",
    url: "https://amzn.to/3SevroM",
    author: "Robert Greene",
    author_url: "https://amzn.to/3f1uH8b",
    asin: "",
    isbn10: "014312417X",
    read: true,
    rating: 4.1,
  },
  {
    name: "The 48 Laws of Power",
    image: "https://images-na.ssl-images-amazon.com/images/I/71aG+xDKSYL.jpg",
    url: "https://amzn.to/3LqE25D",
    author: "Robert Greene",
    author_url: "https://amzn.to/3f1uH8b",
    asin: "",
    isbn10: "0140280197",
    read: true,
    rating: 4.2,
  },
  {
    name: "How to Build a Billion Dollar App",
    image: "https://images-na.ssl-images-amazon.com/images/I/41XGYS-ziEL.jpg",
    url: "https://amzn.to/3eRAE7x",
    author: "George Berkowski",
    author_url: "https://amzn.to/3DzHOb3",
    asin: "0349401373",
    isbn10: "",
    read: true,
    rating: 3,
  },
  {
    name: "Getting Things Done",
    image: "https://images-na.ssl-images-amazon.com/images/I/41YJyWQCBZL.jpg",
    url: "https://amzn.to/3qRKAk9",
    author: "David Allen",
    author_url: "https://amzn.to/3f4wQzS",
    asin: "0142000280",
    isbn10: "",
    read: true,
    rating: 4,
  },
  {
    name: "Smarter Faster Better: The Transformative Power of Real Productivity",
    image: "https://m.media-amazon.com/images/P/081299339X.01._SCLZZZZZZZ_SX500_.jpg",
    url: "https://amzn.to/3UoThzV",
    author: "Charles Duhigg",
    author_url: "https://amzn.to/3UmOcIq",
    asin: "",
    isbn10: "0812983599",
    read: true,
    rating: 4,
  },
  {
    name: "Grit: The Power of Passion and Perseverance",
    image: "https://images-na.ssl-images-amazon.com/images/I/51r1FcTxyhL.jpg",
    url: "https://amzn.to/3LtpQsr",
    author: "Angela Duckworth",
    author_url: "https://amzn.to/3qU9U9n",
    asin: "",
    isbn10: "1501111108",
    read: true,
    rating: 4.5,
  },
  {
    name: "Deep Work: Rules for Focused Success in a Distracted World",
    image: "https://images-na.ssl-images-amazon.com/images/I/71g8BUSqbpL.jpg",
    url: "https://amzn.to/3qNd9PX",
    author: "Cal Newport",
    author_url: "https://amzn.to/3QQN9h2",
    asin: "",
    isbn10: "0349411905",
    read: false,
    rating: 0,
  },
  {
    name: "The Upside of Irrationality: The Unexpected Benefits of Defying Logic at Work and at Home",
    image: "https://images-na.ssl-images-amazon.com/images/I/51ucv9nGv7L.jpg",
    url: "https://amzn.to/3SfVnk2",
    author: "Dan Ariely",
    author_url: "https://amzn.to/3LujAkh",
    asin: "",
    isbn10: "0061995037",
    read: false,
    rating: 0,
  },
  {
    name: "JavaScript and jQuery: Interactive Front-End Web Development",
    image: "https://images-na.ssl-images-amazon.com/images/I/4119l82gW1L.jpg",
    url: "https://amzn.to/3QV6fmb",
    author: "Jon Duckett",
    author_url: "https://amzn.to/3S7YOsW",
    asin: "",
    isbn10: "9781118871652",
    read: true,
    rating: 4,
  },
  {
    name: "JHTML and CSS: Design and Build Websites",
    image: "https://images-na.ssl-images-amazon.com/images/I/31Aj-vC4y-L.jpg",
    url: "https://amzn.to/3dyjMCt",
    author: "Jon Duckett",
    author_url: "https://amzn.to/3S7YOsW",
    asin: "",
    isbn10: "1118871642",
    read: true,
    rating: 4,
  },
  {
    name: "Homo Deus: A History of Tomorrow",
    image: "https://images-na.ssl-images-amazon.com/images/I/81hMjlT14ML.jpg",
    url: "https://amzn.to/3qTDLyO",
    author: "Yuval Noah Harari",
    author_url: "https://amzn.to/3Uq9m8u",
    asin: "",
    isbn10: "0062464345",
    read: true,
    rating: 4.2,
  },
  {
    name: "21 Lessons for the 21st Century",
    image: "https://images-na.ssl-images-amazon.com/images/I/71M2fm6UiVL.jpg",
    url: "https://amzn.to/3BoR6DY",
    author: "Yuval Noah Harari",
    author_url: "https://amzn.to/3Uq9m8u",
    asin: "",
    isbn10: "0062464345",
    read: true,
    rating: 3.3,
  },
  {
    name: "Sapiens: A Brief History of Humankind",
    image: "https://images-na.ssl-images-amazon.com/images/I/71N3-FFSDxL.jpg",
    url: "https://amzn.to/3qP3SGY",
    author: "Yuval Noah Harari",
    author_url: "https://amzn.to/3Uq9m8u",
    asin: "",
    isbn10: "9780062316110",
    read: true,
    rating: 4.6,
  },
  {
    name: "The Science of Getting Rich",
    image: "https://images-na.ssl-images-amazon.com/images/I/81sLZDKj1jL.jpg",
    url: "https://amzn.to/3BSR4pd",
    author: "Wallace D. Wattles",
    author_url: "https://amzn.to/3Se4Vfe",
    asin: "",
    isbn10: "1585426016",
    read: true,
    rating: 4,
  },
  {
    name: "Time to Think: Listening to Ignite the Human Mind",
    image: "https://m.media-amazon.com/images/I/41Z8Z6A5q4L._SY346_.jpg",
    url: "https://amzn.to/3dtnhKC",
    author: "Nancy Kline",
    author_url: "https://amzn.to/3DCWJBb",
    asin: "",
    isbn10: "1788402987",
    read: true,
    rating: 4.8,
  },
  {
    name: "Time Management (Collins Business Secrets)",
    image: "https://images-na.ssl-images-amazon.com/images/I/512GAhO8gCS.jpg",
    url: "https://amzn.to/3xBsgQm",
    author: "Martin H. Manser",
    author_url: "https://amzn.to/3QZ5Mzr",
    asin: "",
    isbn10: "0007324464",
    read: true,
    rating: 2.7,
  },
  {
    name: "Creativity, Inc.",
    image: "https://images-na.ssl-images-amazon.com/images/I/819JSdLa3OL.jpg",
    url: "https://amzn.to/3BwAPwT",
    author: "Ed Catmull",
    author_url: "https://amzn.to/3UqLa5W",
    asin: "",
    isbn10: "0812993012",
    read: true,
    rating: 4.7,
  },
  {
    name: "Linchpin: Are You Indispensable?",
    image: "https://images-na.ssl-images-amazon.com/images/I/61MTYF-Dk+L.jpg",
    url: "https://amzn.to/3qTIjoS",
    author: "Seth Godin",
    author_url: "https://amzn.to/3dvUQM8",
    asin: "",
    isbn10: "0749953659",
    read: true,
    rating: 4.1,
  },
  {
    name: "The Practice",
    image: "https://images-na.ssl-images-amazon.com/images/I/81ZHbjWLqfL.jpg",
    url: "https://amzn.to/3Lri3LM",
    author: "Seth Godin",
    author_url: "https://amzn.to/3dvUQM8",
    asin: "",
    isbn10: "0593328973",
    read: true,
    rating: 2.6,
  },
  {
    name: "Purple Cow",
    image: "https://images-na.ssl-images-amazon.com/images/I/61NbkYP0mEL.jpg",
    url: "https://amzn.to/3BSN2gx",
    author: "Seth Godin",
    author_url: "https://amzn.to/3dvUQM8",
    asin: "",
    isbn10: "9780141016405",
    read: true,
    rating: 4.2,
  },
  {
    name: "Tribes",
    image: "https://images-na.ssl-images-amazon.com/images/I/71Qrh5uB3BL.jpg",
    url: "https://amzn.to/3f89jyk",
    author: "Seth Godin",
    author_url: "https://amzn.to/3dvUQM8",
    asin: "",
    isbn10: "9780749939755",
    read: true,
    rating: 3.8,
  },
  {
    name: "The Power of Habit",
    image: "https://images-na.ssl-images-amazon.com/images/I/81oc6I4sn-L.jpg",
    url: "https://amzn.to/3UhNLPP",
    author: "Charles Duhigg",
    author_url: "https://amzn.to/3UmOcIq",
    asin: "",
    isbn10: "1400069289",
    read: true,
    rating: 4.5,
  },
  {
    name: "Thinking for a Change",
    image: "https://images-na.ssl-images-amazon.com/images/I/81kz4fiAWzL.jpg",
    url: "https://amzn.to/3Rc8ZvP",
    author: "John C. Maxwell",
    author_url: "https://amzn.to/3QSfjrT",
    asin: "",
    isbn10: "0446692883",
    read: true,
    rating: 4,
  },
  {
    name: "Blink: The Power of Thinking Without Thinking",
    image: "https://images-na.ssl-images-amazon.com/images/I/61bYyB1I+UL.jpg",
    url: "https://amzn.to/3xCPyoH",
    author: "Malcolm Gladwell",
    author_url: "https://amzn.to/3dqyAmN",
    asin: "",
    isbn10: "0316172324",
    read: true,
    rating: 4.2,
  },
  {
    name: "Outliers: The Story of Success",
    image: "https://images-na.ssl-images-amazon.com/images/I/71PP92fxyEL.jpg",
    url: "https://amzn.to/3QXOgLK",
    author: "Malcolm Gladwell",
    author_url: "https://amzn.to/3dqyAmN",
    asin: "",
    isbn10: "0316017930",
    read: true,
    rating: 4.8,
  },
  {
    name: "The Tipping Point: How Little Things Can Make a Big Differenceg",
    image: "https://images-na.ssl-images-amazon.com/images/I/71vzpPj921L.jpg",
    url: "https://amzn.to/3eRL6Mj",
    author: "Malcolm Gladwell",
    author_url: "https://amzn.to/3dqyAmN",
    asin: "",
    isbn10: "0316346624",
    read: true,
    rating: 4.5,
  },
  {
    name: "What the Dog Saw: And Other Adventures",
    image: "https://images-na.ssl-images-amazon.com/images/I/61j+kOX7c2L.jpg",
    url: "https://amzn.to/3eZyz9M",
    author: "Malcolm Gladwell",
    author_url: "https://amzn.to/3dqyAmN",
    asin: "",
    isbn10: "0316076201",
    read: true,
    rating: 3.6,
  },
  {
    name: "David and Goliath: Underdogs, Misfits and the Art of Battling Giants",
    image: "https://images-na.ssl-images-amazon.com/images/I/71L5SRRo3KL.jpg",
    url: "https://amzn.to/3f5ZUat",
    author: "Malcolm Gladwell",
    author_url: "https://amzn.to/3dqyAmN",
    asin: "",
    isbn10: "0316204374",
    read: true,
    rating: 4,
  },
  {
    name: "True North: Discover Your Authentic Leadership",
    image: "https://images-na.ssl-images-amazon.com/images/I/51+N6nYLVfL.jpg",
    url: "https://amzn.to/3f3NZdc",
    author: "Bill George",
    author_url: "https://amzn.to/3BRg00w",
    asin: "",
    isbn10: "0787987514",
    read: true,
    rating: 3.2,
  },
  {
    name: "Sprint: How to Solve Big Problems and Test New Ideas in Just Five Days",
    image: "https://images-na.ssl-images-amazon.com/images/I/81xBzG4riDL.jpg",
    url: "https://amzn.to/3QXS6ov",
    author: "Jake Knapp",
    author_url: "https://amzn.to/3SzBdSj",
    asin: "",
    isbn10: "0593076117",
    read: false,
    rating: 0,
  },
  {
    name: "Inspired: How to Create Tech Products Customers Love",
    image: "https://images-na.ssl-images-amazon.com/images/I/416vIaW8Q8L.jpg",
    url: "https://amzn.to/3RQA3Sh",
    author: "Marty Cagan",
    author_url: "https://amzn.to/3UnqnQT",
    asin: "",
    isbn10: "1119387507",
    read: false,
    rating: 0,
  },
  {
    name: "Elon Musk: Tesla, SpaceX, and the Quest for a Fantastic Future",
    image: "https://images-na.ssl-images-amazon.com/images/I/5112YFsXIJL.jpg",
    url: "https://amzn.to/3Bu5MSj",
    author: "Ashlee Vance",
    author_url: "https://amzn.to/3eXoeuV",
    asin: "",
    isbn10: "006230125X",
    read: false,
    rating: 0,
  },
  {
    name: "Kitchen Confidential: Adventures in the Culinary Underbelly",
    image: "https://m.media-amazon.com/images/I/51IvNQ71JJL.jpg",
    url: "https://amzn.to/3BvXhpI",
    author: "Anthony Bourdain",
    author_url: "https://amzn.to/3f4ohVZ",
    asin: "",
    isbn10: "0060899220",
    read: true,
    rating: 4.6,
  },
  {
    name: "Rogue Trader",
    image: "https://images-na.ssl-images-amazon.com/images/I/51KIkdCSSLL.jpg",
    url: "https://amzn.to/3eSKsy8",
    author: "Nick Leeson",
    author_url: "https://amzn.to/3BTyX2F",
    asin: "",
    isbn10: "9780751563399",
    read: true,
    rating: 4.1,
  },
  {
    name: "Six Thinking Hats",
    image: "https://images-na.ssl-images-amazon.com/images/I/41ZkI9dpcCL.jpg",
    url: "https://amzn.to/3Bu096G",
    author: "Edward De Bono",
    author_url: "https://amzn.to/3RTrXbw",
    asin: "",
    isbn10: "0140296662",
    read: true,
    rating: 3.6,
  },
  {
    name: "Lateral Thinking",
    image: "https://images-na.ssl-images-amazon.com/images/I/5174JtKAAmL.jpg",
    url: "https://amzn.to/3Um7ePb",
    author: "Edward De Bono",
    author_url: "https://amzn.to/3RTrXbw",
    asin: "",
    isbn10: "0060903252",
    read: true,
    rating: 4.2,
  },
  {
    name: "Thinking, Fast and Slow",
    image: "https://images-na.ssl-images-amazon.com/images/I/61n7jZ8xQ6L.jpg",
    url: "https://amzn.to/3UkW2T0",
    author: "Daniel Kahneman",
    author_url: "https://amzn.to/3RW2LB3",
    asin: "",
    isbn10: "0374275637",
    read: true,
    rating: 3.9,
  },
  {
    name: "Awaken the Giant Within",
    image: "https://images-na.ssl-images-amazon.com/images/I/81KkKgd18LL.jpg",
    url: "https://amzn.to/3SewTHR",
    author: "Tony Robbins",
    author_url: "https://amzn.to/3BQ0wK5",
    asin: "",
    isbn10: "0671791540",
    read: true,
    rating: 4,
  },
  {
    name: "The Autobiography of Benjamin Franklin",
    image: "https://images-na.ssl-images-amazon.com/images/I/71jAKz597+L.jpg",
    url: "https://amzn.to/3QSlqMR",
    author: "Benjamin Franklin",
    author_url: "https://amzn.to/3Byp3SN",
    asin: "",
    isbn10: "1640320024",
    read: true,
    rating: 2.8,
  },
  {
    name: "Steve Jobs",
    image: "https://images-na.ssl-images-amazon.com/images/I/81VStYnDGrL.jpg",
    url: "https://amzn.to/3f3cSpn",
    author: "Walter Isaacson",
    author_url: "https://amzn.to/3LtBMuz",
    asin: "",
    isbn10: "1451648537",
    read: true,
    rating: 4.5,
  },
  {
    name: "Benjamin Franklin: An American Life",
    image: "https://images-na.ssl-images-amazon.com/images/I/A1yfTyslOOL.jpg",
    url: "https://amzn.to/3RZMgEm",
    author: "Walter Isaacson",
    author_url: "https://amzn.to/3LtBMuz",
    asin: "",
    isbn10: "1451648537",
    read: true,
    rating: 3.5,
  },
  {
    name: "Images of Organization",
    image: "https://m.media-amazon.com/images/P/1412939798.01._SCLZZZZZZZ_SX500_.jpg",
    url: "https://amzn.to/3LptaFb",
    author: "Gareth Morgan",
    author_url: "https://amzn.to/3SdNgoB",
    asin: "",
    isbn10: "1412939798",
    read: true,
    rating: 4,
  },
  {
    name: "Diagnosing and Changing Organizational Culture",
    image: "https://images-na.ssl-images-amazon.com/images/I/51ArsJr2ePL.jpg",
    url: "https://amzn.to/3SfYiJf",
    author: "Kim S. Cameron & Robert E. Quinn",
    author_url: "https://amzn.to/3xBzHHg",
    asin: "",
    isbn10: "0787982830",
    read: true,
    rating: 3.6,
  },
  {
    name: "Quiet: The Power of Introverts in a World That Can't Stop Talking",
    image: "https://images-na.ssl-images-amazon.com/images/I/71uL+QKtoJL.jpg",
    url: "https://amzn.to/3BTRCez",
    author: "Susan Cain",
    author_url: "https://amzn.to/3Bp2r70",
    asin: "",
    isbn10: "0307352145",
    read: true,
    rating: 3.9,
  },
  {
    name: "Learning Web Design: A Beginner's Guide to (X)HTML, StyleSheets, and Web Graphics",
    image: "https://images-na.ssl-images-amazon.com/images/I/513uzQH5TCL.jpg",
    url: "https://amzn.to/3ScyZYw",
    author: "Jennifer Niederst Robbins",
    author_url: "https://amzn.to/3qRY3J2",
    asin: "",
    isbn10: "0596527527",
    read: true,
    rating: 4.4,
  },
  {
    name: "The Art of War",
    image: "https://images-na.ssl-images-amazon.com/images/I/61enryG3nTL.jpg",
    url: "https://amzn.to/3UrcCAP",
    author: "Sun Tzu",
    author_url: "https://amzn.to/3qOItxA",
    asin: "",
    isbn10: "0595224725",
    read: true,
    rating: 4.2,
  },
  {
    name: "Drive: The Surprising Truth About What Motivates Us",
    image: "https://images-na.ssl-images-amazon.com/images/I/81-JlsOu0fL.jpg",
    url: "https://amzn.to/3xDZluJ",
    author: "Daniel H. Pink",
    author_url: "https://amzn.to/3RYje85",
    asin: "",
    isbn10: "9781594488849",
    read: true,
    rating: 4,
  },
  {
    name: "Science of Self Discipline",
    image:
      "https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1422804009i/3224947.jpg",
    url: "https://amzn.to/3RZM8EH",
    author: "Dr. Kerry L. Johnson",
    author_url: "",
    asin: "",
    isbn10: "",
    read: true,
    rating: 3.2,
  },
  {
    name: "The Magic of Thinking Big",
    image: "https://images-na.ssl-images-amazon.com/images/I/61gTbU67c+L.jpg",
    url: "https://amzn.to/3Lrq43k",
    author: "David J. Schwartz",
    author_url: "https://amzn.to/3BrYhex",
    asin: "",
    isbn10: "0671646788",
    read: true,
    rating: 3.8,
  },
  {
    name: "First Things First",
    image: "https://images-na.ssl-images-amazon.com/images/I/71PXJZwa8BL.jpg",
    url: "https://amzn.to/3Lru042",
    author: "Stephen R. Covey",
    author_url: "https://amzn.to/3BrYGO5",
    asin: "",
    isbn10: "9780684802039",
    read: true,
    rating: 4.2,
  },
  {
    name: "The 7 Habits of Highly Effective People",
    image: "https://images-na.ssl-images-amazon.com/images/I/81bgPVZOAUL.jpg",
    url: "https://amzn.to/3xBod6e",
    author: "Stephen R. Covey",
    author_url: "https://amzn.to/3BrYGO5",
    asin: "",
    isbn10: "1471195201",
    read: true,
    rating: 5,
  },
  {
    name: "The 8th Habit",
    image: "https://images-na.ssl-images-amazon.com/images/I/71ZW2wGvBnL.jpg",
    url: "https://amzn.to/3xBG2Cs",
    author: "Stephen R. Covey",
    author_url: "https://amzn.to/3BrYGO5",
    asin: "",
    isbn10: "0743287932",
    read: true,
    rating: 4.9,
  },
  {
    name: "Primary Greatness",
    image: "https://images-na.ssl-images-amazon.com/images/I/61beVUqGFLL.jpg",
    url: "https://amzn.to/3dtwGBU",
    author: "Stephen R. Covey",
    author_url: "https://amzn.to/3BrYGO5",
    asin: "",
    isbn10: "1501106589",
    read: true,
    rating: 3.8,
  },
  {
    name: "The Effective Executive",
    image: "https://images-na.ssl-images-amazon.com/images/I/619O1ieMN4L.jpg",
    url: "https://amzn.to/3DUtmdZ",
    author: "Peter F. Drucker",
    author_url: "https://amzn.to/3BQ2pq9",
    asin: "",
    isbn10: "0060833459",
    read: true,
    rating: 4,
  },
  {
    name: "How to Stop Worrying and Start Living",
    image: "https://images-na.ssl-images-amazon.com/images/I/718EanL0ZcL.jpg",
    url: "https://amzn.to/3RVWhCz",
    author: "Dale Carnegie",
    author_url: "https://amzn.to/3RYk70p",
    asin: "",
    isbn10: "0671035975",
    read: true,
    rating: 4.1,
  },
  {
    name: "How to Win Friends and Influence People",
    image: "https://images-na.ssl-images-amazon.com/images/I/61GhStIMcSL.jpg",
    url: "https://amzn.to/3xExZ7Y",
    author: "Dale Carnegie",
    author_url: "https://amzn.to/3RYk70p",
    asin: "",
    isbn10: "0091947464",
    read: true,
    rating: 4.6,
  },
  {
    name: "Less: Accomplishing More by Doing Less",
    image: "https://images-na.ssl-images-amazon.com/images/I/414LlKbFNLL.jpg",
    url: "https://amzn.to/3QWYmN8",
    author: "Marc Lesser",
    author_url: "https://amzn.to/3qPMYrA",
    asin: "",
    isbn10: "1577316177",
    read: true,
    rating: 3.4,
  },
  {
    name: "A Short History of Nearly Everything",
    image: "https://m.media-amazon.com/images/I/51G0i4rqVFL.jpg",
    url: "https://amzn.to/3xChTvj",
    author: "Bill Bryson",
    author_url: "https://amzn.to/3qSyPdo",
    asin: "",
    isbn10: "0767908171",
    read: true,
    rating: 4.7,
  },
  {
    name: "Leaders Eat Last",
    image: "https://images-na.ssl-images-amazon.com/images/I/815wOrM8ukL.jpg",
    url: "https://amzn.to/3UmXCUo",
    author: "Simon Sinek",
    author_url: "https://amzn.to/3dvCWsP",
    asin: "",
    isbn10: "1591845327",
    read: true,
    rating: 4.4,
  },
  {
    name: "Start With Why",
    image: "https://images-na.ssl-images-amazon.com/images/I/71K9EcfzJ4L.jpg",
    url: "https://amzn.to/3RWxiPf",
    author: "Simon Sinek",
    author_url: "https://amzn.to/3dvCWsP",
    asin: "",
    isbn10: "9781591846444",
    read: true,
    rating: 4.5,
  },
  {
    name: "The E-Myth Revisited",
    image: "https://images-na.ssl-images-amazon.com/images/I/71K9EcfzJ4L.jpg",
    url: "https://amzn.to/3eYmilX",
    author: "Michael E. Gerber",
    author_url: "https://amzn.to/3DIQgF3",
    asin: "",
    isbn10: "9780887307287",
    read: true,
    rating: 4.8,
  },
  {
    name: "Man's Search for Meaning",
    image: "https://images-na.ssl-images-amazon.com/images/I/71M9Lo9yb9L.jpg",
    url: "https://amzn.to/3qTB4wU",
    author: "Viktor E. Frankl",
    author_url: "https://amzn.to/3BVUyaQ",
    asin: "",
    isbn10: "0807092150",
    read: true,
    rating: 4.3,
  },
  {
    name: "Never Eat Alone",
    image: "https://m.media-amazon.com/images/I/51g98XrdQiL.jpg",
    url: "https://amzn.to/3QTq0KR",
    author: "Keith Ferrazzi",
    author_url: "https://amzn.to/3Byrm8p",
    asin: "",
    isbn10: "0553418769",
    read: true,
    rating: 2.9,
  },
  {
    name: "Little Red Book of Selling: 12.5 Principles of Sales Greatness",
    image: "https://images-na.ssl-images-amazon.com/images/I/91-1qV3oRfL.jpg",
    url: "https://amzn.to/3SmpWVf",
    author: "Jeffrey Gitomer",
    author_url: "https://amzn.to/3SjzU9W",
    asin: "",
    isbn10: "1885167601",
    read: true,
    rating: 3.4,
  },
  {
    name: "Zero to One: Notes on Startups, or How to Build the Future",
    image: "https://m.media-amazon.com/images/I/41PZRSHF-NL.jpg",
    url: "https://amzn.to/3BTFF8R",
    author: "Peter Thiel & Blake Masters",
    author_url: "https://amzn.to/3QYruDM",
    asin: "",
    isbn10: "0753555190",
    read: true,
    rating: 4.8,
  },
  {
    name: "The Art of the Start",
    image: "https://images-na.ssl-images-amazon.com/images/I/71lRMoScSlL.jpg",
    url: "https://amzn.to/3UAVJ6T",
    author: "Guy Kawasaki",
    author_url: "https://amzn.to/3Ui0Vwd",
    asin: "",
    isbn10: "1591840562",
    read: true,
    rating: 3.4,
  },
  {
    name: "Powers of Two",
    image: "https://images-na.ssl-images-amazon.com/images/I/51Ts4l62sTL.jpg",
    url: "https://amzn.to/3DA1viZ",
    author: "Joshua Wolf Shenk",
    author_url: "https://amzn.to/3xBKiSs",
    asin: "",
    isbn10: "0544031598",
    read: true,
    rating: 4.3,
  },
  {
    name: "Good to Great",
    image: "https://images-na.ssl-images-amazon.com/images/I/913d0uqSoPL.jpg",
    url: "https://amzn.to/3BOHuCT",
    author: "James C. Collins",
    author_url: "https://amzn.to/3QVtLiP",
    asin: "",
    isbn10: "9780066620992",
    read: true,
    rating: 4.2,
  },
  {
    name: "Built to Last",
    image: "https://images-na.ssl-images-amazon.com/images/I/61-+RJemWdL.jpg",
    url: "https://amzn.to/3UnKNt2",
    author: "James C. Collins",
    author_url: "https://amzn.to/3QVtLiP",
    asin: "",
    isbn10: "0060516402",
    read: true,
    rating: 4.4,
  },
  {
    name: "Influence: The Psychology of Persuasion",
    image: "https://images-na.ssl-images-amazon.com/images/I/81PIXB1RBEL.jpg",
    url: "https://amzn.to/3SaHyDy",
    author: "Robert B. Cialdini",
    author_url: "https://amzn.to/3QX2OLQ",
    asin: "",
    isbn10: "006124189X",
    read: true,
    rating: 4.5,
  },
  {
    name: "Emotional Intelligence",
    image: "https://images-na.ssl-images-amazon.com/images/I/71dvXxQcUML.jpg",
    url: "https://amzn.to/3dmX54o",
    author: "Daniel Goleman",
    author_url: "https://amzn.to/3Bw5TN4",
    asin: "",
    isbn10: "055380491X",
    read: true,
    rating: 2.8,
  },
  {
    name: "The 4-Hour Chef",
    image: "https://images-na.ssl-images-amazon.com/images/I/61mIt0JA7aL.jpg",
    url: "https://amzn.to/3SfPfrV",
    author: "Timothy Ferriss",
    author_url: "https://amzn.to/3xDajki",
    asin: "",
    isbn10: "1328519163",
    read: true,
    rating: 4.6,
  },
  {
    name: "The 4-Hour Body",
    image: "https://images-na.ssl-images-amazon.com/images/I/718yDjorBpL.jpg",
    url: "https://amzn.to/3RZ4MwA",
    author: "Timothy Ferriss",
    author_url: "https://amzn.to/3xDajki",
    asin: "",
    isbn10: "1328519163",
    read: true,
    rating: 3.8,
  },
  {
    name: "The 4-Hour Work Week",
    image: "https://images-na.ssl-images-amazon.com/images/I/81qW97ndkvL.jpg",
    url: "https://amzn.to/3eSWeZm",
    author: "Timothy Ferriss",
    author_url: "https://amzn.to/3xDajki",
    asin: "",
    isbn10: "9780091929114",
    read: true,
    rating: 4.4,
  },
  {
    name: "Tools of Titans",
    image: "https://images-na.ssl-images-amazon.com/images/I/81Qaq2O8dsL.jpg",
    url: "https://amzn.to/3Bmq9AQ",
    author: "Timothy Ferriss",
    author_url: "https://amzn.to/3xDajki",
    asin: "",
    isbn10: "9780091929114",
    read: true,
    rating: 4,
  },
  {
    name: "Tribe of Mentors",
    image: "https://images-na.ssl-images-amazon.com/images/I/81EBZkpP+kL.jpg",
    url: "https://amzn.to/3Lus5f3",
    author: "Timothy Ferriss",
    author_url: "https://amzn.to/3xDajki",
    asin: "",
    isbn10: "9780091929114",
    read: true,
    rating: 3.2,
  },
  {
    name: "Hooked",
    image: "https://images-na.ssl-images-amazon.com/images/I/81fcWvYdukL.jpg",
    url: "https://amzn.to/3Up6Dfz",
    author: "Nir Eyal",
    author_url: "https://amzn.to/3LqSquF",
    asin: "",
    isbn10: "1591847788",
    read: true,
    rating: 4.6,
  },
  {
    name: "Indistractable",
    image: "https://images-na.ssl-images-amazon.com/images/I/71yV71FUIAS.jpg",
    url: "https://amzn.to/3UpEQeX",
    author: "Nir Eyal",
    author_url: "https://amzn.to/3LqSquF",
    asin: "",
    isbn10: "1591847788",
    read: true,
    rating: 4.1,
  },
];
