export const CV = {
  name: "Felix Tellmann",
  address: "Cape Town, Vredehoek 8001, South Africa",
  email: "hello@flext.dev",
  mobile: "+27760313590",
  eduction: [
    {
      dateFrom: "1992",
      dateTo: "1996",
      city: "Mönchengladbach",
      country: "Germany",
      institution: "Primary School Gertraudenstraße",
      certificate: "Primary School Certificate",
      level: "School",
    },
    {
      dateFrom: "1996",
      dateTo: "2002",
      city: "Mönchengladbach",
      country: "Germany",
      institution: "Comprehensive School Espenstraße",
      certificate: "Secondary School Certificate",
      level: "School",
    },
    {
      dateFrom: "2002",
      dateTo: "2004",
      city: "Mönchengladbach",
      country: "Germany",
      institution: "Vocational College of Technology and Media",
      certificate: "High School Certificate",
      level: "School",
    },
    {
      dateFrom: "2008",
      dateTo: "2008",
      city: "Cape Town",
      country: "South Africa",
      institution: "International Hotel School",
      certificate: "Skills, Tasks and Result Training Certificate",
      level: "Higher Education",
    },
    {
      dateFrom: "2009",
      dateTo: "2012",
      city: "Cape Town",
      country: "South Africa",
      institution: "International Hotel School",
      certificate: "Higher Diploma in Professional Cookery & Kitchen Management",
      level: "Higher Education",
    },
    {
      dateFrom: "2009",
      dateTo: "2012",
      city: "Cape Town",
      country: "South Africa",
      institution: "International Hotel School",
      certificate: "Higher Diploma in Food & Beverage Management",
      level: "Higher Education",
    },
    {
      dateFrom: "2013",
      dateTo: "2013",
      city: "Cape Town",
      country: "South Africa",
      institution: "International Hotel School",
      certificate: "Higher Diploma in Hospitality Management",
      level: "Higher Education",
    },
    {
      dateFrom: "2015",
      dateTo: "2015",
      city: "Cape Town",
      country: "South Africa",
      institution: "University of Cape Town",
      certificate: "Postgraduate Diploma in Business Management & Entrepreneurship",
      level: "Higher Education",
    },
  ],
  experience: [
    {
      dateFrom: "2005/01",
      dateTo: "2005/07",
      city: "Mönchengladbach",
      country: "Germany",
      company: "Internet Café Matrix",
      title: "IT Technical Assistant",
      responsibilities: [],
    },
    {
      dateFrom: "2005/07",
      dateTo: "2006/03",
      city: "Mönchengladbach",
      country: "Germany",
      company: "Social Holding Mönchengladbach",
      title: "Volunteer Delivery Driver",
      responsibilities: [],
    },
    {
      dateFrom: "2006/05",
      dateTo: "2007/06",
      city: "Mönchengladbach",
      country: "Germany",
      company: "Schröder & Tellmann Design Agency",
      title: "Internship in Media & Graphic Design",
      responsibilities: [],
    },
    {
      dateFrom: "2008/01",
      dateTo: "2008/07",
      city: "Cape Town",
      country: "South Africa",
      company: "Cape Milner Hotel",
      title: "Front-Office, Housekeeping and Food & Beverage Training",
      responsibilities: [],
    },
    {
      dateFrom: "2008/08",
      dateTo: "2008/12",
      city: "Düsseldorf",
      country: "Germany",
      company: "Monkey's Gastronomy",
      title: "Apprenticeship as a Chef",
      responsibilities: [],
    },
    {
      dateFrom: "2009/02",
      dateTo: "2009/06",
      city: "Cape Town",
      country: "South Africa",
      company: "Cape Milner Hotel",
      title: "Assistant Front-Office Manager",
      responsibilities: [],
    },
    {
      dateFrom: "2009/07",
      dateTo: "2010/06",
      city: "Cape Town",
      country: "South Africa",
      company: "The Winchester Mansion Hotel",
      title: "Junior Chef de Partie",
      responsibilities: [],
    },
    {
      dateFrom: "2010/02",
      dateTo: "2018/01",
      city: "Cape Town",
      country: "South Africa",
      company: "33 Degrees - Catering & Events",
      title: "Founder & Caterer",
      responsibilities: [],
    },
    {
      dateFrom: "2010/07",
      dateTo: "2011/06",
      city: "Cape Town",
      country: "South Africa",
      company: "The Mount Restaurant",
      title: "Chef de Partie / Junior Sous-Chef",
      responsibilities: [],
    },
    {
      dateFrom: "2011/11",
      dateTo: "2012/05",
      city: "Cape Town",
      country: "South Africa",
      company: "The Yachts of Seabourn – Six-Star Cruise Line",
      title: "Waiter / Buffet Manager",
      responsibilities: [],
    },
    {
      dateFrom: "2012/08",
      dateTo: "2013/05",
      city: "Cape Town",
      country: "South Africa",
      company: "Salt Restaurant",
      title: "Assistant Restaurant Manager",
      responsibilities: [],
    },
    {
      dateFrom: "2013/07",
      dateTo: "2015/01",
      city: "Cape Town",
      country: "South Africa",
      company: "Kitima Restaurant",
      title: "Restaurant Manager",
      responsibilities: [],
    },
    {
      dateFrom: "2015/02",
      dateTo: "2015/10",
      city: "Cape Town",
      country: "South Africa",
      company: "Kitima Restaurant",
      title: "Consulting Manager",
      responsibilities: [],
    },
    {
      dateFrom: "2015/02",
      dateTo: "2015/10",
      city: "Cape Town",
      country: "South Africa",
      company: "Simply Stuck - Vinyl Accessories",
      title: "Co-Founder & Product Development Lead",
      responsibilities: [],
    },
    {
      dateFrom: "2015/11",
      dateTo: "2016/05",
      city: "Cape Town",
      country: "South Africa",
      company: "Raya Kitchen by Kitima",
      title: "General Manager",
      responsibilities: [],
    },
    {
      dateFrom: "2016/06",
      dateTo: "2017/03",
      city: "Cape Town",
      country: "South Africa",
      company: "SmartUp Online (Pty) Ltd. - Restaurant Training & Development",
      title: "Co-Founder & Managing Director / Lead Engineer",
      responsibilities: [],
    },
    {
      dateFrom: "2017/03",
      dateTo: "2018/06",
      city: "Cape Town",
      country: "South Africa",
      company: "Liquix (Pty) Ltd. – Web Design Studio",
      title: "Co-Founder, Managing Director / Lead Engineer",
      responsibilities: [],
    },
    {
      dateFrom: "2018/07",
      dateTo: "2020/04",
      city: "Knysna",
      country: "South Africa",
      company: "The Burger Exchange (Pty) Ltd",
      title: "Co-Founder, Managing Director",
      responsibilities: [],
    },
    {
      dateFrom: "2018/07",
      dateTo: "2020/04",
      city: "Cape Town",
      country: "South Africa",
      company: "Tellmann – Web Design Studio",
      title: "Founder & Principal Full-Stack Engineer",
      responsibilities: [],
    },
  ],
  development: [
    {
      date: "",
      name: "",
      location: "",
    },
  ],
  certifications: [
    {
      date: "",
      name: "",
      location: "",
    },
  ],
  languages: [
    {
      language: "German",
      proficiency: "native",
    },
    {
      language: "English",
      proficiency: "Bilingual",
    },
    {
      language: "French",
      proficiency: "Basic",
    },
  ],
  skills: [{}],
  frameworks: [{}],
};
